name: Python Scaper Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule to run every 24 hours at midnight
  workflow_dispatch: # Manual trigger

jobs:
  run-webscraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Run webscraper.py
      run: python webscraper.py
